### ISSUE TITLE
is:issue is:open Dota2.py的11行你暴露了自己的SteamWebAPI的KEY

### ISSUE THREAD

**Issue by phoneixSH** [Inv0k3r/dota2_csgo_watcher_bot#1]
还是改成可配置的然后删了吧,否则别人用你的KEY进行高频率访问,那大家都会返回429拿不到信息的.
另外10W的限制我初测应该是每分钟60次左右,这几个月收集了DOTA2所有的比赛信息统计后估出来的.
而且跨IP同KEY是这个频率,单IP不同KEY应该也是这个频率.

**Comment by Inv0k3r** [comment]
可以, 忘了这茬了, 改了改了
