### ISSUE TITLE
list.json 问题

### ISSUE THREAD

**Issue by greenhaha** [Inv0k3r/dota2_csgo_watcher_bot#2]
list.json 里面的账号  是指的什么账号  昵称是群员昵称  后面的数字具体是指什么账号

**Comment by Inv0k3r** [comment]
就是游戏里加好友的时候用的那个账号，在游戏里点添加好友可以看到

**Comment by greenhaha** [comment]
是steam账号吗  还是 qq账号   还有一个地方不明白 就是

message_sender.py  中

**Comment by Inv0k3r** [comment]
就dota里加好友的时候用的那个号

**Comment by Inv0k3r** [comment]
authkey是在mirai http的配置文件里设置的，你应该先弄好mirai http

**Comment by greenhaha** [comment]
![Uploading image.png…]()
