### ISSUE TITLE
文件应该放到哪个文件夹啊

### ISSUE THREAD

**Issue by huoranxuanyuan** [Inv0k3r/dota2_csgo_watcher_bot#3]
![image](https://user-images.githubusercontent.com/67738326/96740479-740e3180-13f3-11eb-922a-0ee02a5f8ca8.png)
这些文件应该放在哪呢，别的步骤都弄好了
![image](https://user-images.githubusercontent.com/67738326/96740598-8ee0a600-13f3-11eb-9a57-1538d6fc062f.png)
代码也全是问号不知道写的啥、、

**Comment by Inv0k3r** [comment]
这些py放哪里都可以 直接运行就行

图二应该是miraiok运行起来的样子

第一次运行完产生plugins以后关掉，第二次运行输入 login QQ号 密码 就可以登录bot了

**Comment by huoranxuanyuan** [comment]
> 这些py放哪里都可以 直接运行就行
> 
> 图二应该是miraiok运行起来的样子
> 
> 第一次运行完产生plugins以后关掉，第二次运行输入 login QQ号 密码 就可以登录bot了

![image](https://user-images.githubusercontent.com/67738326/96742053-0e22a980-13f5-11eb-90fa-f16320e085a4.png)
哦哦，这应该就算运行成功了吧？怎么测试一下呢，打一盘时间实在有点长。

**Comment by Inv0k3r** [comment]
用python3运行。。你这个是py2报错了，dbq我没在readme写清楚

**Comment by huoranxuanyuan** [comment]
> 用python3运行。。你这个是py2报错了，dbq我没在readme写清楚

![image](https://user-images.githubusercontent.com/67738326/96744004-27c4f080-13f7-11eb-9073-67f20e648cb8.png)
![Uploading image.png…]()
我升级了还是报错。。

**Comment by huoranxuanyuan** [comment]
> 用python3运行。。你这个是py2报错了，dbq我没在readme写清楚

![image](https://user-images.githubusercontent.com/67738326/96744166-5642cb80-13f7-11eb-9885-10fc282e901f.png)
![image](https://user-images.githubusercontent.com/67738326/96744181-5a6ee900-13f7-11eb-91e8-56691f5e162d.png)
我升级了还是报错、、

**Comment by exckot** [comment]
你好，遇到同样问题，升级为python3.9.0后运行显示
![5}LJG7`O5GE0NATA7ABV16W](https://user-images.githubusercontent.com/18240080/96775768-98313900-141a-11eb-9976-4d08451abca9.png)

**Comment by Inv0k3r** [comment]
pip install requests
