### ISSUE TITLE
萌新提问运行问题

### ISSUE THREAD

**Issue by exckot** [Inv0k3r/dota2_csgo_watcher_bot#4]
出现了和前面朋友相同的问题
![5}LJG7`O5GE0NATA7ABV16W](https://user-images.githubusercontent.com/18240080/96776018-fcec9380-141a-11eb-96cb-4b9cad6bafc9.png)

顺便问下在关闭ssh客户端后，程序是否会在后台继续运行，还是说我需要用到screen来后台运行呢？

**Comment by Inv0k3r** [comment]
通过pip install requests安装模块
我用的是screen放后台运行
