### ISSUE TITLE
好友账号是个人资料的uid还是好友码啊？

### ISSUE THREAD

**Issue by xiaobaozi233** [Inv0k3r/dota2_csgo_watcher_bot#6]
如果是好友码就需要找别人要了吧...

**Comment by Inv0k3r** [comment]
实际上在max+点开个人资料, 昵称下面会写steamID: xxxxx

比如我们点开max的知名玩家那里, 可以看到FG的ID是90045009

但是我建议还是跟群友直接要, 毕竟有人不想被加入
