### ISSUE TITLE
list.json 编码格式的问题

### ISSUE THREAD

**Issue by xiaobaozi233** [Inv0k3r/dota2_csgo_watcher_bot#7]
刚自己改ID后发现读取报错了
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 53: illegal multibyte sequence

把run.py里
json.load(open("list.json", "r")
改成
open("list.json", "r",encoding='UTF-8')
就可以了...

**Comment by Inv0k3r** [comment]
已修复
