### ISSUE TITLE
要不原来的教程还是放出来吧，想搭windows的

### ISSUE THREAD

**Issue by SlatedFish-QAQ** [Inv0k3r/dota2_csgo_watcher_bot#8]
请求把原来的教程放出来，并且在git中添加所需要的资源，比如jar即各版本的exe。希望后续由win下面的一键部署脚本，多谢大佬啦。（要资源是因为没有java的编译环境.jpg）

**Comment by SlatedFish-QAQ** [comment]
还有就是config.json中的api_key是要填写啥东西啊

**Comment by Inv0k3r** [comment]
已加回安装步骤, exe各种版本自行去链接地址下吧
